<?php
$data = array (
  536 => 
  array (
    'cat_id' => '536',
    'cat_name' => '水果蔬菜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '536',
    'name' => '水果蔬菜',
  ),
  555 => 
  array (
    'cat_id' => '555',
    'cat_name' => '水果',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '555',
    'name' => '水果',
  ),
  556 => 
  array (
    'cat_id' => '556',
    'cat_name' => '蔬菜',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '556',
    'name' => '蔬菜',
  ),
  542 => 
  array (
    'cat_id' => '542',
    'cat_name' => '中药材',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '542',
    'name' => '中药材',
  ),
  543 => 
  array (
    'cat_id' => '543',
    'cat_name' => '党参',
    'measure_unit' => '',
    'parent_id' => '542',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '543',
    'name' => '党参',
  ),
  544 => 
  array (
    'cat_id' => '544',
    'cat_name' => '金银花',
    'measure_unit' => '',
    'parent_id' => '542',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '544',
    'name' => '金银花',
  ),
  539 => 
  array (
    'cat_id' => '539',
    'cat_name' => '农副加工',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '539',
    'name' => '农副加工',
  ),
  550 => 
  array (
    'cat_id' => '550',
    'cat_name' => '肉蛋奶',
    'measure_unit' => '',
    'parent_id' => '539',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '550',
    'name' => '肉蛋奶',
  ),
  549 => 
  array (
    'cat_id' => '549',
    'cat_name' => '酒茶冲饮',
    'measure_unit' => '',
    'parent_id' => '539',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '549',
    'name' => '酒茶冲饮',
  ),
  540 => 
  array (
    'cat_id' => '540',
    'cat_name' => '苗木花草',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '540',
    'name' => '苗木花草',
  ),
  548 => 
  array (
    'cat_id' => '548',
    'cat_name' => '花卉盆栽',
    'measure_unit' => '',
    'parent_id' => '540',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '548',
    'name' => '花卉盆栽',
  ),
  547 => 
  array (
    'cat_id' => '547',
    'cat_name' => '苗木',
    'measure_unit' => '',
    'parent_id' => '540',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '547',
    'name' => '苗木',
  ),
  537 => 
  array (
    'cat_id' => '537',
    'cat_name' => '畜牧水产',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '537',
    'name' => '畜牧水产',
  ),
  553 => 
  array (
    'cat_id' => '553',
    'cat_name' => '禽畜类',
    'measure_unit' => '',
    'parent_id' => '537',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '553',
    'name' => '禽畜类',
  ),
  554 => 
  array (
    'cat_id' => '554',
    'cat_name' => '水产类',
    'measure_unit' => '',
    'parent_id' => '537',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '554',
    'name' => '水产类',
  ),
  541 => 
  array (
    'cat_id' => '541',
    'cat_name' => '农资农机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '541',
    'name' => '农资农机',
  ),
  545 => 
  array (
    'cat_id' => '545',
    'cat_name' => '农资',
    'measure_unit' => '',
    'parent_id' => '541',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '545',
    'name' => '农资',
  ),
  546 => 
  array (
    'cat_id' => '546',
    'cat_name' => '农机',
    'measure_unit' => '',
    'parent_id' => '541',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '546',
    'name' => '农机',
  ),
  538 => 
  array (
    'cat_id' => '538',
    'cat_name' => '粮油米面',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '538',
    'name' => '粮油米面',
  ),
  551 => 
  array (
    'cat_id' => '551',
    'cat_name' => '五谷杂粮',
    'measure_unit' => '',
    'parent_id' => '538',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '551',
    'name' => '五谷杂粮',
  ),
  552 => 
  array (
    'cat_id' => '552',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '538',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '552',
    'name' => '食用油',
  ),
);
?>